import SwiftUI
import Charts

struct ContentView: View {
    @EnvironmentObject var s: BudgetStore
    @State private var addExpense=false
    var body: some View {
        TabView {
            NavigationStack { Dashboard(addExpense:$addExpense) }.tabItem { Label("الرئيسية",systemImage:"house.fill") }
            NavigationStack { TransactionsView(addExpense:$addExpense) }.tabItem { Label("العمليات",systemImage:"arrow.left.arrow.right") }
            NavigationStack { PlanningView() }.tabItem { Label("التخطيط",systemImage:"target") }
            NavigationStack { ReportsView() }.tabItem { Label("التقارير",systemImage:"chart.bar.xaxis") }
            NavigationStack { SettingsView() }.tabItem { Label("الإعدادات",systemImage:"gearshape.fill") }
        }
        .tint(.indigo).environment(\.layoutDirection,.rightToLeft)
        .sheet(isPresented:$addExpense){AddExpense()}
    }
}

struct Dashboard: View {
    @EnvironmentObject var s: BudgetStore; @Binding var addExpense:Bool
    var body: some View { ScrollView { VStack(spacing:18) {
        HStack { VStack(alignment:.leading,spacing:4){Text("ميزانيتي").font(.largeTitle.bold());Text(Date.now.formatted(.dateTime.month(.wide).year())).foregroundStyle(.secondary)};Spacer(); ZStack{Circle().fill(.indigo.opacity(0.12)).frame(width:52,height:52);Image(systemName:"wallet.bifold.fill").font(.title2).foregroundStyle(.indigo)} }
        VStack(spacing:8){ Text("تقدر تصرف اليوم").foregroundStyle(.secondary); Text(s.dailyLimit,format:.currency(code:"SAR")).font(.system(size:43,weight:.bold,design:.rounded)).contentTransition(.numericText()); HStack(spacing:6){Image(systemName:s.todaySpent<=s.dailyLimit ? "checkmark.circle.fill":"exclamationmark.triangle.fill"); Text(statusText)}.font(.subheadline.bold()).foregroundStyle(s.todaySpent<=s.dailyLimit ? .green:.red) }.glassCard()
        HStack(spacing:12){Metric(title:"متبقي الشهر",value:s.remaining,icon:"banknote.fill");Metric(title:"صرفت هذا الشهر",value:s.spent,icon:"arrow.up.right.circle.fill")}
        Button { addExpense=true } label:{Label("إضافة مصروف",systemImage:"plus").font(.headline).frame(maxWidth:.infinity).padding(.vertical,14)}.buttonStyle(.borderedProminent).buttonBorderShape(.roundedRectangle(radius:18))
        VStack(alignment:.leading,spacing:14){HStack{Label("حالة الميزانية",systemImage:"gauge.with.dots.needle.67percent").font(.headline);Spacer();Text("\(Int(s.health*100))٪").bold()};ProgressView(value:s.health).tint(s.health > 0.35 ? .green : .orange); Divider(); HStack{mini("الالتزامات",s.fixed);Spacer();mini("الادخار",s.suggestedSaving);Spacer();mini("أيام متبقية",Double(s.daysLeft),currency:false)}}.glassCard()
        VStack(alignment:.leading,spacing:12){Label("آخر 7 أيام",systemImage:"chart.xyaxis.line").font(.headline); Chart(s.last7Days,id:\.0){item in BarMark(x:.value("اليوم",item.0,unit:.day),y:.value("الصرف",item.1)).cornerRadius(5)}.frame(height:150).chartYAxis(.hidden)}.glassCard()
        SmartInsight().glassCard()
    }.padding() }.navigationBarHidden(true) }
    var statusText:String { s.todaySpent<=s.dailyLimit ? "باقي لك اليوم \(s.safeTodayRemaining.formatted(.number.precision(.fractionLength(0)))) ر.س" : "متجاوز حد اليوم بـ \((s.todaySpent-s.dailyLimit).formatted(.number.precision(.fractionLength(0)))) ر.س" }
    func mini(_ t:String,_ v:Double,currency:Bool=true)->some View{VStack(alignment:.leading,spacing:4){Text(t).font(.caption).foregroundStyle(.secondary); if currency{Text(v,format:.currency(code:"SAR")).font(.subheadline.bold())}else{Text("\(Int(v))").font(.subheadline.bold())}}}
}

struct SmartInsight:View{@EnvironmentObject var s:BudgetStore;var body:some View{VStack(alignment:.leading,spacing:8){Label("تحليل ذكي",systemImage:"sparkles").font(.headline);Text(message).foregroundStyle(.secondary).font(.subheadline)}};var message:String{if s.salary<=0{return "أدخل راتبك والتزاماتك أولًا لأبني لك خطة صرف يومية دقيقة."};if s.remaining<0{return "ميزانية الصرف تجاوزت المتاح. راجع أكبر تصنيف صرف أو خفّض هدف الادخار مؤقتًا."};if s.projectedEndBalance<s.endGoal{return "بمعدل صرفك الحالي قد تنهي الشهر بأقل من هدفك. خفض المتوسط اليومي خلال الأيام القادمة."};return "معدل صرفك الحالي متوافق مع الخطة. استمرارك بهذا الإيقاع يحافظ على هدف نهاية الشهر."}}}
struct Metric:View{let title:String;let value:Double;let icon:String;var body:some View{VStack(alignment:.leading,spacing:8){Image(systemName:icon).foregroundStyle(.indigo);Text(title).font(.caption).foregroundStyle(.secondary);Text(value,format:.currency(code:"SAR")).font(.headline).minimumScaleFactor(0.7)}.frame(maxWidth:.infinity,alignment:.leading).glassCard()}}

struct TransactionsView:View{@EnvironmentObject var s:BudgetStore;@Binding var addExpense:Bool;@State private var search="";var filtered:[Expense]{s.monthExpenses.sorted{$0.date>$1.date}.filter{search.isEmpty || $0.category.localizedCaseInsensitiveContains(search) || $0.note.localizedCaseInsensitiveContains(search)}};var body:some View{List{Section{Button{addExpense=true}label:{Label("تسجيل مصروف جديد",systemImage:"plus.circle.fill")}};Section("هذا الشهر — \(s.spent.formatted(.number.precision(.fractionLength(0)))) ر.س"){if filtered.isEmpty{ContentUnavailableView("لا توجد عمليات",systemImage:"tray",description:Text("أضف أول مصروف وسيظهر هنا."))};ForEach(filtered){e in HStack(spacing:12){Image(systemName:icon(e.category)).frame(width:34,height:34).background(.indigo.opacity(0.1),in:Circle()).foregroundStyle(.indigo);VStack(alignment:.leading){Text(e.category).bold();if !e.note.isEmpty{Text(e.note).font(.caption).foregroundStyle(.secondary)};Text(e.date.formatted(date:.abbreviated,time:.shortened)).font(.caption2).foregroundStyle(.tertiary)};Spacer();Text(e.amount,format:.currency(code:"SAR")).bold()}.swipeActions{Button(role:.destructive){s.deleteExpense(e.id)}label:{Label("حذف",systemImage:"trash")}}}}}.searchable(text:$search,prompt:"ابحث في المصاريف").navigationTitle("العمليات").toolbar{Button{addExpense=true}label:{Image(systemName:"plus")}}};func icon(_ c:String)->String{["طعام":"fork.knife","قهوة":"cup.and.saucer.fill","وقود":"fuelpump.fill","تسوق":"bag.fill","ترفيه":"gamecontroller.fill","فواتير":"bolt.fill" ][c] ?? "square.grid.2x2.fill"}}

struct PlanningView:View{@EnvironmentObject var s:BudgetStore;@State var addCommit=false;@State var addGoal=false;var body:some View{List{Section("الخطة الشهرية"){MoneyField(title:"صافي الراتب",value:$s.salary);MoneyField(title:"هدف نهاية الشهر",value:$s.endGoal);HStack{Text("نسبة الادخار");Spacer();Text(s.savingRate,format:.percent.precision(.fractionLength(0)))};Slider(value:$s.savingRate,in:0...0.5,step:0.05)};Section{HStack{Text("إجمالي الالتزامات");Spacer();Text(s.fixed,format:.currency(code:"SAR")).bold()};ForEach(s.commitments){c in HStack{VStack(alignment:.leading){Text(c.title);Text("استحقاق يوم \(c.dueDay) • \(c.category)").font(.caption).foregroundStyle(.secondary)};Spacer();Text(c.amount,format:.currency(code:"SAR"))}}.onDelete{s.commitments.remove(atOffsets:$0)};Button{addCommit=true}label:{Label("إضافة التزام",systemImage:"plus")}}header:{Text("الالتزامات المتكررة")};Section{ForEach(s.goals){g in VStack(alignment:.leading,spacing:7){HStack{Text(g.title).bold();Spacer();Text("\(Int(g.current)) / \(Int(g.target)) ر.س").font(.caption)};ProgressView(value:g.target>0 ? min(1,g.current/g.target):0)}}.onDelete{s.goals.remove(atOffsets:$0)};Button{addGoal=true}label:{Label("إضافة هدف ادخار",systemImage:"plus")}}header:{Text("أهداف الادخار")}}.navigationTitle("التخطيط").sheet(isPresented:$addCommit){AddCommitment()}.sheet(isPresented:$addGoal){AddGoal()}}}

struct ReportsView:View{@EnvironmentObject var s:BudgetStore;var body:some View{ScrollView{VStack(spacing:16){VStack(alignment:.leading,spacing:12){Text("الصرف حسب التصنيف").font(.headline);if s.categoryTotals.isEmpty{Text("لا توجد بيانات كافية بعد").foregroundStyle(.secondary).frame(maxWidth:.infinity,minHeight:120)}else{Chart(s.categoryTotals,id:\.0){x in SectorMark(angle:.value("الصرف",x.1),innerRadius:.ratio(0.58),angularInset:2).foregroundStyle(by:.value("التصنيف",x.0))}.frame(height:220)}}.glassCard();VStack(alignment:.leading,spacing:10){Text("تفاصيل التصنيفات").font(.headline);ForEach(s.categoryTotals,id:\.0){x in HStack{Text(x.0);Spacer();Text(x.1,format:.currency(code:"SAR")).bold();Text(s.spent>0 ? "\(Int(x.1/s.spent*100))٪":"0٪").font(.caption).foregroundStyle(.secondary)}}}.glassCard();VStack(alignment:.leading,spacing:10){Text("توقع نهاية الشهر").font(.headline);Text(s.projectedEndBalance,format:.currency(code:"SAR")).font(.title.bold());Text("تقدير مبني على متوسط صرفك الحالي، وليس ضمانًا للمبلغ النهائي.").font(.caption).foregroundStyle(.secondary)}.glassCard()}.padding()}.navigationTitle("التقارير")}}

struct SettingsView:View{@EnvironmentObject var s:BudgetStore;@State var confirm=false;var body:some View{Form{Section("الراتب"){Stepper("يوم نزول الراتب: \(s.payday)",value:$s.payday,in:1...28)};Section("التجربة"){Toggle("الاهتزازات",isOn:$s.haptics)};Section("طريقة الحساب"){Text("يُخصم من الراتب: الالتزامات + الادخار + هدف نهاية الشهر. ثم تُخصم مصاريف الشهر، ويُوزع المتبقي على الأيام الباقية.").foregroundStyle(.secondary)};Section{Button("مسح مصاريف الشهر",role:.destructive){confirm=true}}}.navigationTitle("الإعدادات").confirmationDialog("مسح جميع مصاريف هذا الشهر؟",isPresented:$confirm,titleVisibility:.visible){Button("مسح",role:.destructive){s.resetMonth()}}}}

struct MoneyField:View{let title:String;@Binding var value:Double;var body:some View{HStack{Text(title);Spacer();TextField("0",value:$value,format:.number).keyboardType(.decimalPad).multilineTextAlignment(.leading).frame(maxWidth:110);Text("ر.س").foregroundStyle(.secondary)}}}
struct AddExpense:View{@EnvironmentObject var s:BudgetStore;@Environment(\.dismiss)var dismiss;@State var amount=0.0;@State var category="طعام";@State var note="";@State var date=Date();let cats=["طعام","قهوة","وقود","تسوق","ترفيه","فواتير","أخرى"];var body:some View{NavigationStack{Form{Section("المبلغ"){MoneyField(title:"المصروف",value:$amount)};Section("التفاصيل"){Picker("التصنيف",selection:$category){ForEach(cats,id:\.self){Text($0)}};TextField("ملاحظة (اختياري)",text:$note);DatePicker("التاريخ",selection:$date,in:...Date())}}.navigationTitle("مصروف جديد").toolbar{ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("حفظ"){if amount>0{s.expenses.append(.init(amount:amount,category:category,note:note,date:date));dismiss()}}.bold()}}}}}
struct AddCommitment:View{@EnvironmentObject var s:BudgetStore;@Environment(\.dismiss)var dismiss;@State var title="";@State var amount=0.0;@State var category="أخرى";@State var due=1;var body:some View{NavigationStack{Form{TextField("اسم الالتزام",text:$title);MoneyField(title:"المبلغ الشهري",value:$amount);Picker("النوع",selection:$category){ForEach(["سكن","سيارة/تمويل","فواتير","عائلة","اشتراكات","أخرى"],id:\.self){Text($0)}};Stepper("يوم الاستحقاق: \(due)",value:$due,in:1...28)}.navigationTitle("التزام جديد").toolbar{ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("حفظ"){if !title.isEmpty && amount>0{s.commitments.append(.init(title:title,amount:amount,category:category,dueDay:due));dismiss()}}}}}}}
struct AddGoal:View{@EnvironmentObject var s:BudgetStore;@Environment(\.dismiss)var dismiss;@State var title="";@State var target=0.0;@State var current=0.0;var body:some View{NavigationStack{Form{TextField("مثال: صندوق طوارئ",text:$title);MoneyField(title:"الهدف",value:$target);MoneyField(title:"المبلغ الحالي",value:$current)}.navigationTitle("هدف ادخار").toolbar{ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("حفظ"){if !title.isEmpty && target>0{s.goals.append(.init(title:title,target:target,current:current));dismiss()}}}}}}}
extension View{func glassCard()->some View{self.padding(16).background(.thinMaterial,in:RoundedRectangle(cornerRadius:24,style:.continuous)).overlay(RoundedRectangle(cornerRadius:24).stroke(.primary.opacity(0.07))).shadow(color:.black.opacity(0.035),radius:12,y:5)}}
